package model.views;

import java.sql.Connection;
import java.io.*;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.sql.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;


/**
 * creamos los objetos de la base de datos.
 */
public class Vista extends javax.swing.JFrame {

    Conectadb sqlite;
    Connection con;
    private File escribe;

    /**
     * generamos conección.
     */
    public Vista() {
        initComponents();
        sqlite = new Conectadb();
        con = sqlite.Conectar();
        jPanel4.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPasswordField2 = new javax.swing.JPasswordField();
        jComboBox2 = new javax.swing.JComboBox();
        jButton17 = new javax.swing.JButton();
        jPasswordField3 = new javax.swing.JPasswordField();
        jLabel28 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jButton24 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel40 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton15 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jLabel41 = new javax.swing.JLabel();
        jButton23 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jButton16 = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton10 = new javax.swing.JButton();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jButton21 = new javax.swing.JButton();
        jLabel34 = new javax.swing.JLabel();
        jTextField21 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton11 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jButton22 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        jLabel27 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jButton18 = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jButton19 = new javax.swing.JButton();
        jLabel31 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jButton20 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(72, 141, 215));
        setMinimumSize(new java.awt.Dimension(610, 550));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(72, 141, 215));
        jPanel1.setMinimumSize(new java.awt.Dimension(610, 550));
        jPanel1.setName(""); // NOI18N
        jPanel1.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(59, 157, 196));
        jPanel4.setMinimumSize(new java.awt.Dimension(610, 495));
        jPanel4.setLayout(null);

        jLabel1.setText("Registrarse");
        jPanel4.add(jLabel1);
        jLabel1.setBounds(250, 60, 90, 14);

        jLabel2.setText("id");
        jPanel4.add(jLabel2);
        jLabel2.setBounds(180, 170, 40, 14);

        jLabel3.setText("contraseña");
        jPanel4.add(jLabel3);
        jLabel3.setBounds(170, 240, 90, 14);

        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton1);
        jButton1.setBounds(250, 390, 110, 23);

        jButton2.setText("login");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2);
        jButton2.setBounds(410, 390, 90, 23);
        jPanel4.add(jTextField1);
        jTextField1.setBounds(310, 160, 120, 30);
        jPanel4.add(jPasswordField2);
        jPasswordField2.setBounds(310, 230, 120, 30);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "empleado", "cliente", "gerente" }));
        jPanel4.add(jComboBox2);
        jComboBox2.setBounds(230, 100, 120, 30);

        jButton17.setText("Atras");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton17);
        jButton17.setBounds(110, 390, 90, 23);
        jPanel4.add(jPasswordField3);
        jPasswordField3.setBounds(310, 300, 120, 30);

        jLabel28.setText("confirmar contraseña");
        jPanel4.add(jLabel28);
        jLabel28.setBounds(160, 310, 130, 14);

        jLabel35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel4.add(jLabel35);
        jLabel35.setBounds(490, 0, 120, 110);

        jButton24.setText("Generar informe ultimo registro");
        jButton24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton24ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton24);
        jButton24.setBounds(150, 440, 270, 23);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 0, 610, 495);

        jPanel2.setBackground(new java.awt.Color(59, 155, 196));
        jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel2.setMinimumSize(new java.awt.Dimension(610, 495));
        jPanel2.setLayout(null);

        jLabel4.setText("Login");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(260, 80, 60, 20);

        jLabel5.setText("id");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(180, 160, 30, 14);

        jLabel6.setText("contraseña");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(150, 250, 100, 14);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(310, 150, 130, 30);
        jPanel2.add(jPasswordField1);
        jPasswordField1.setBounds(310, 240, 130, 30);

        jButton3.setText("ingresar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(260, 370, 110, 23);

        jLabel36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel2.add(jLabel36);
        jLabel36.setBounds(490, 0, 120, 113);

        jLabel45.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.add(jLabel45);
        jLabel45.setBounds(210, 300, 270, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 610, 495);

        jPanel3.setBackground(new java.awt.Color(72, 141, 215));
        jPanel3.setMinimumSize(new java.awt.Dimension(610, 495));
        jPanel3.setPreferredSize(new java.awt.Dimension(610, 495));
        jPanel3.setLayout(null);

        jLabel7.setText("Nombre Producto");
        jPanel3.add(jLabel7);
        jLabel7.setBounds(110, 90, 120, 14);

        jLabel8.setText("Precio Producto");
        jPanel3.add(jLabel8);
        jLabel8.setBounds(110, 140, 130, 14);

        jLabel9.setText("Cantidad Producto comprados");
        jPanel3.add(jLabel9);
        jLabel9.setBounds(100, 190, 180, 14);

        jLabel10.setText("Referencia");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(110, 240, 90, 14);

        jLabel11.setText("Numero de articulos vendidos");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(110, 290, 170, 14);

        jLabel12.setText("Cantidad total");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(110, 340, 110, 14);
        jPanel3.add(jTextField3);
        jTextField3.setBounds(350, 80, 120, 20);
        jPanel3.add(jTextField4);
        jTextField4.setBounds(350, 130, 120, 20);
        jPanel3.add(jTextField5);
        jTextField5.setBounds(350, 190, 120, 20);
        jPanel3.add(jTextField6);
        jTextField6.setBounds(350, 240, 120, 20);
        jPanel3.add(jTextField7);
        jTextField7.setBounds(350, 290, 120, 20);
        jPanel3.add(jTextField8);
        jTextField8.setBounds(350, 330, 120, 20);

        jLabel13.setText("Inventario");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(250, 40, 90, 14);

        jButton4.setBackground(new java.awt.Color(57, 57, 28));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/images.png"))); // NOI18N
        jButton4.setText("Guardar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4);
        jButton4.setBounds(230, 400, 120, 33);

        jButton5.setText("Consultar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5);
        jButton5.setBounds(410, 400, 100, 23);

        jButton14.setText("Salir");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton14);
        jButton14.setBounds(80, 400, 80, 23);

        jLabel40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel3.add(jLabel40);
        jLabel40.setBounds(490, 0, 120, 110);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(0, 0, 610, 495);

        jPanel5.setBackground(new java.awt.Color(72, 141, 215));
        jPanel5.setMinimumSize(new java.awt.Dimension(610, 495));
        jPanel5.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("Cuentas por cobrar");
        jPanel5.add(jLabel16);
        jLabel16.setBounds(220, 80, 136, 17);

        jLabel14.setText("nombre cliente ");
        jPanel5.add(jLabel14);
        jLabel14.setBounds(140, 170, 100, 14);
        jPanel5.add(jTextField12);
        jTextField12.setBounds(360, 220, 120, 20);

        jLabel15.setText("nombre articulo");
        jPanel5.add(jLabel15);
        jLabel15.setBounds(140, 220, 110, 14);
        jPanel5.add(jTextField13);
        jTextField13.setBounds(360, 270, 120, 20);

        jLabel17.setText("cantidad de deuda");
        jPanel5.add(jLabel17);
        jLabel17.setBounds(140, 280, 130, 14);
        jPanel5.add(jTextField9);
        jTextField9.setBounds(360, 160, 120, 20);

        jButton6.setText("Consultar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton6);
        jButton6.setBounds(460, 410, 110, 23);

        jButton7.setBackground(new java.awt.Color(0, 0, 0));
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/images.png"))); // NOI18N
        jButton7.setText("Guardar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton7);
        jButton7.setBounds(290, 410, 130, 33);

        jLabel18.setText("Gerente");
        jPanel5.add(jLabel18);
        jLabel18.setBounds(260, 40, 90, 14);

        jButton15.setText("Salir");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton15);
        jButton15.setBounds(30, 410, 70, 23);

        jButton13.setText("Registrar");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton13);
        jButton13.setBounds(140, 410, 110, 23);

        jLabel41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel5.add(jLabel41);
        jLabel41.setBounds(490, 0, 119, 113);

        jButton23.setText("Generar reporte");
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton23);
        jButton23.setBounds(230, 340, 130, 23);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(0, 0, 610, 495);

        jPanel6.setBackground(new java.awt.Color(72, 141, 215));
        jPanel6.setMinimumSize(new java.awt.Dimension(610, 495));
        jPanel6.setLayout(null);

        jLabel19.setText("Cantidad");
        jPanel6.add(jLabel19);
        jLabel19.setBounds(130, 130, 90, 14);

        jLabel20.setText("Fecha");
        jPanel6.add(jLabel20);
        jLabel20.setBounds(130, 190, 90, 14);

        jLabel21.setText("Nombre ");
        jPanel6.add(jLabel21);
        jLabel21.setBounds(130, 250, 90, 14);

        jLabel22.setText("Direccion");
        jPanel6.add(jLabel22);
        jLabel22.setBounds(130, 310, 100, 14);
        jPanel6.add(jTextField11);
        jTextField11.setBounds(310, 130, 140, 20);
        jPanel6.add(jTextField10);
        jTextField10.setBounds(310, 190, 140, 20);
        jPanel6.add(jTextField14);
        jTextField14.setBounds(310, 250, 140, 20);
        jPanel6.add(jTextField15);
        jTextField15.setBounds(310, 310, 140, 20);

        jLabel23.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel23.setText("Compras");
        jPanel6.add(jLabel23);
        jLabel23.setBounds(260, 80, 100, 17);

        jButton8.setText("Consultar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton8);
        jButton8.setBounds(390, 390, 90, 23);

        jButton9.setBackground(new java.awt.Color(0, 0, 0));
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/images.png"))); // NOI18N
        jButton9.setText("Guardar");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton9);
        jButton9.setBounds(240, 390, 120, 33);

        jLabel24.setText("Cliente");
        jPanel6.add(jLabel24);
        jLabel24.setBounds(270, 40, 80, 14);

        jButton16.setText("Salir");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel6.add(jButton16);
        jButton16.setBounds(120, 390, 70, 23);

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel6.add(jLabel42);
        jLabel42.setBounds(490, 0, 119, 113);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 610, 495);

        jPanel7.setBackground(new java.awt.Color(72, 141, 215));
        jPanel7.setMinimumSize(new java.awt.Dimension(610, 495));
        jPanel7.setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cantidad", "fecha", "nombre", "direccion"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel7.add(jScrollPane1);
        jScrollPane1.setBounds(100, 20, 400, 140);

        jButton10.setText("Atras");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton10);
        jButton10.setBounds(260, 450, 100, 23);

        jLabel32.setText("atributo actualizar");
        jPanel7.add(jLabel32);
        jLabel32.setBounds(50, 310, 110, 20);

        jLabel33.setText("nueva valor");
        jPanel7.add(jLabel33);
        jLabel33.setBounds(330, 310, 80, 14);
        jPanel7.add(jTextField19);
        jTextField19.setBounds(170, 300, 120, 30);
        jPanel7.add(jTextField20);
        jTextField20.setBounds(430, 300, 120, 30);

        jButton21.setText("Actualizar");
        jButton21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton21ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton21);
        jButton21.setBounds(240, 400, 150, 23);

        jLabel34.setText("nombre del dato a actualizar");
        jPanel7.add(jLabel34);
        jLabel34.setBounds(120, 220, 160, 14);
        jPanel7.add(jTextField21);
        jTextField21.setBounds(290, 210, 140, 30);

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel7.add(jLabel43);
        jLabel43.setBounds(490, 380, 119, 113);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(0, 0, 610, 495);

        jPanel8.setBackground(new java.awt.Color(72, 141, 215));
        jPanel8.setMinimumSize(new java.awt.Dimension(610, 495));
        jPanel8.setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " producto", "precio ", "cantidad comprados", "referencia", " articulos vendidos", "cantidad total"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel8.add(jScrollPane2);
        jScrollPane2.setBounds(0, 0, 610, 130);

        jButton11.setText("Atras");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton11);
        jButton11.setBounds(240, 440, 100, 23);

        jLabel37.setText("nombre producto a actualizar");
        jPanel8.add(jLabel37);
        jLabel37.setBounds(100, 170, 170, 14);

        jLabel38.setText("nuevo valor");
        jPanel8.add(jLabel38);
        jLabel38.setBounds(100, 300, 80, 20);

        jLabel39.setText("atributo a actualizar");
        jPanel8.add(jLabel39);
        jLabel39.setBounds(100, 240, 110, 14);
        jPanel8.add(jTextField22);
        jTextField22.setBounds(310, 160, 110, 30);
        jPanel8.add(jTextField23);
        jTextField23.setBounds(310, 230, 110, 30);
        jPanel8.add(jTextField24);
        jTextField24.setBounds(310, 290, 110, 30);

        jButton22.setText("Actualizar");
        jButton22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton22ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton22);
        jButton22.setBounds(240, 370, 100, 23);

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo.png"))); // NOI18N
        jPanel8.add(jLabel44);
        jLabel44.setBounds(490, 380, 119, 110);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, 0, 610, 495);

        jPanel9.setBackground(new java.awt.Color(72, 141, 215));
        jPanel9.setMinimumSize(new java.awt.Dimension(610, 550));
        jPanel9.setLayout(null);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " producto", "precio ", "cantidad comprados", "referencia", " articulos vendidos", "cantidad total"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel9.add(jScrollPane3);
        jScrollPane3.setBounds(0, 30, 610, 100);

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "cantidad", "fecha", "nombre", "direccion"
            }
        ));
        jScrollPane4.setViewportView(jTable4);

        jPanel9.add(jScrollPane4);
        jScrollPane4.setBounds(10, 200, 600, 90);

        jLabel25.setText("inventario");
        jPanel9.add(jLabel25);
        jLabel25.setBounds(260, 10, 110, 14);

        jLabel26.setText("Compras");
        jPanel9.add(jLabel26);
        jLabel26.setBounds(270, 180, 80, 14);

        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre deudor ", "nombre articulo", "cantidad deuda"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel9.add(jScrollPane5);
        jScrollPane5.setBounds(10, 360, 600, 90);

        jLabel27.setText("gerente");
        jPanel9.add(jLabel27);
        jLabel27.setBounds(280, 340, 70, 14);

        jButton12.setText("Atras");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton12);
        jButton12.setBounds(270, 500, 80, 23);

        jLabel29.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        jLabel29.setText("Nombre producto a eliminar");
        jPanel9.add(jLabel29);
        jLabel29.setBounds(40, 140, 160, 20);
        jPanel9.add(jTextField16);
        jTextField16.setBounds(240, 140, 170, 30);

        jButton18.setText("Eliminar");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton18);
        jButton18.setBounds(460, 140, 100, 23);

        jLabel30.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel30.setText("Nombre de la compra a eliminar");
        jPanel9.add(jLabel30);
        jLabel30.setBounds(20, 300, 210, 14);
        jPanel9.add(jTextField17);
        jTextField17.setBounds(240, 300, 170, 30);

        jButton19.setText("Eliminar");
        jButton19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton19ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton19);
        jButton19.setBounds(460, 300, 100, 23);

        jLabel31.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        jLabel31.setText("Nombre deudor a eliminar");
        jPanel9.add(jLabel31);
        jLabel31.setBounds(30, 460, 190, 14);
        jPanel9.add(jTextField18);
        jTextField18.setBounds(250, 460, 160, 30);

        jButton20.setText("Eliminar");
        jButton20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton20ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton20);
        jButton20.setBounds(460, 460, 100, 23);

        jPanel1.add(jPanel9);
        jPanel9.setBounds(0, 0, 610, 550);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 495, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Date d = new Date();
        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("ingresa ala interfez login " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
        jPanel4.setVisible(false);
        jPanel2.setVisible(true);
        jTextField1.setText("");
        jPasswordField2.setText("");
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("ingresa ala interfez login");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        Date d = new Date();
        escribe = new File("log.txt");

        if ((jTextField2.getText().trim().isEmpty()) || (jPasswordField1.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(this, "algun campo de texto está vacío");

        } else {
            if (!isInteger(jTextField2.getText())) {
                JOptionPane.showMessageDialog(this, "ingrese un valor numerico");
            } else {

                try {
                    Statement stmt = con.createStatement();
                    ResultSet rs = stmt.executeQuery("select *from registros");
                    String a = jTextField2.getText();
                    String ba = jPasswordField1.getText();

                    while (rs.next()) {
                        if (a.equals(rs.getString(1)) && ba.equals(rs.getString(2))) {
                            if (rs.getString(3).equals("empleado")) {
                                jPanel6.setVisible(false);
                                jPanel4.setVisible(false);
                                jPanel3.setVisible(true);
                                jPanel2.setVisible(false);
                                jPanel5.setVisible(false);
                                jPanel7.setVisible(false);
                                jPanel8.setVisible(false);
                                jPanel9.setVisible(false);
                                System.out.println("se logueo un empleado");
                                System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                                System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                                try {

                                    FileWriter f = new FileWriter(escribe, true);
                                    BufferedWriter b = new BufferedWriter(f);
                                    PrintWriter p = new PrintWriter(b);
                                    p.write("se logueo un empleado " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                                    p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                                    p.append("\r\n");
                                    p.close();
                                    f.close();
                                } catch (IOException e) {

                                }
                            } else if (rs.getString(3).equals("cliente")) {

                                System.out.println("se logueo un cliente");
                                System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                                System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                                jPanel6.setVisible(true);
                                jPanel4.setVisible(false);
                                jPanel3.setVisible(false);
                                jPanel2.setVisible(false);
                                jPanel5.setVisible(false);
                                jPanel7.setVisible(false);
                                jPanel8.setVisible(false);
                                jPanel9.setVisible(false);
                                try {

                                    FileWriter f = new FileWriter(escribe, true);
                                    BufferedWriter b = new BufferedWriter(f);
                                    PrintWriter p = new PrintWriter(b);
                                    p.write("se logueo un cliente " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                                    p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                                    p.append("\r\n");
                                    p.close();
                                    f.close();
                                } catch (IOException e) {

                                }
                            } else if (rs.getString(3).equals("gerente")) {
                                System.out.println("se logueo un gerente");
                                System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                                System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                                jPanel6.setVisible(false);
                                jPanel4.setVisible(false);
                                jPanel3.setVisible(false);
                                jPanel2.setVisible(false);
                                jPanel5.setVisible(true);
                                jPanel7.setVisible(false);
                                jPanel8.setVisible(false);
                                jPanel9.setVisible(false);
                                try {

                                    FileWriter f = new FileWriter(escribe, true);
                                    BufferedWriter b = new BufferedWriter(f);
                                    PrintWriter p = new PrintWriter(b);
                                    p.write("se logueo un gerente " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                                    p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                                    p.append("\r\n");
                                    p.close();
                                    f.close();
                                } catch (IOException e) {

                                }

                            }

                        }else{
                             jLabel45.setText("Contraseña u usuario incorrectos!! ");
                        }
                    }
                    rs.close();
                    stmt.close();
                } catch (SQLException y) {
                    JOptionPane.showMessageDialog(null, y);
                }
                jTextField2.setText("");
                jPasswordField1.setText("");

            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // empleado

        try {
            DefaultTableModel tableModel = (DefaultTableModel) jTable3.getModel();
            Object[] filas = new Object[jTable3.getColumnCount()];
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select *from empleados");
            while (rs.next()) {

                filas[0] = rs.getString(1);
                filas[1] = rs.getInt(2);
                filas[2] = rs.getInt(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getInt(5);
                filas[5] = rs.getInt(6);

                tableModel.addRow(filas);
            }

            rs.close();
            stmt.close();
        } catch (SQLException y) {
            JOptionPane.showMessageDialog(null, y);
        }
        //cliente 

        try {
            DefaultTableModel tableModel = (DefaultTableModel) jTable4.getModel();
            Object[] filas = new Object[jTable4.getColumnCount()];
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select *from clientes");
            while (rs.next()) {

                filas[0] = rs.getInt(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);

                tableModel.addRow(filas);
            }

            rs.close();
            stmt.close();
        } catch (SQLException y) {
            JOptionPane.showMessageDialog(null, y);
        }
        //gerente 

        try {
            DefaultTableModel tableModel = (DefaultTableModel) jTable5.getModel();
            Object[] filas = new Object[jTable5.getColumnCount()];
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select *from cuentas");
            while (rs.next()) {

                filas[0] = rs.getString(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getInt(3);

                tableModel.addRow(filas);
            }

            rs.close();
            stmt.close();
        } catch (SQLException y) {
            JOptionPane.showMessageDialog(null, y);
        }
        jPanel6.setVisible(false);
        jPanel4.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
        jPanel5.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(true);

        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("consulta de las tablas Empleados, Clientes, Cuentas");

        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("consulta de las tablas Empleados, Clientes, Cuentas " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

        if ((jTextField9.getText().trim().isEmpty()) || (jTextField12.getText().trim().isEmpty()) || (jTextField13.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(this, "algun campo de texto está vacío");

        } else {

            if (!isInteger(jTextField13.getText())) {
                JOptionPane.showMessageDialog(this, "ingrese un valor numerico");
            } else {
                try {

                    Statement stmt = con.createStatement();
                    String j = "insert into cuentas values('" + jTextField9.getText() + "','" + jTextField12.getText() + "','" + jTextField13.getText() + "')";
                    int t = stmt.executeUpdate(j);
                    stmt.close();

                } catch (SQLException y) {
                    JOptionPane.showMessageDialog(null, y);
                }

                Date d = new Date();
                System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                System.out.println("Se han insertado en la tabla cuentas los sigientes datos: " + jTextField9.getText() + "','" + jTextField12.getText() + "','" + jTextField13.getText());

                jTextField9.setText("");
                jTextField12.setText("");
                jTextField13.setText("");

                escribe = new File("log.txt");
                try {

                    FileWriter f = new FileWriter(escribe, true);
                    BufferedWriter b = new BufferedWriter(f);
                    PrintWriter p = new PrintWriter(b);
                    p.write("Se han insertado datos en la tabla cuentas : " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                    p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                    p.append("\r\n");
                    p.close();
                    f.close();
                } catch (IOException e) {

                }

            }
        }

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
        Object[] filas = new Object[jTable1.getColumnCount()];
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select *from clientes");
            while (rs.next()) {

                filas[0] = rs.getInt(1);
                filas[1] = rs.getString(2);
                filas[2] = rs.getString(3);
                filas[3] = rs.getString(4);

                tableModel.addRow(filas);
            }
            jPanel6.setVisible(false);
            jPanel4.setVisible(false);
            jPanel3.setVisible(false);
            jPanel2.setVisible(false);
            jPanel5.setVisible(false);
            jPanel7.setVisible(true);
            jPanel8.setVisible(false);
            jPanel9.setVisible(false);

            rs.close();
            stmt.close();
        } catch (SQLException y) {
            JOptionPane.showMessageDialog(null, y);
        }
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("consulta de las tabla Clientes");

        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("consulta de las tabla Clientes " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed

        if ((jTextField11.getText().trim().isEmpty()) || (jTextField10.getText().trim().isEmpty()) || (jTextField14.getText().trim().isEmpty()) || (jTextField15.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(this, "algun campo de texto está vacío");

        } else {

            if (!isInteger(jTextField11.getText())) {
                JOptionPane.showMessageDialog(this, "ingrese un valor numerico");
            } else {

                try {

                    Statement stmt = con.createStatement();
                    String j = "insert into clientes values('" + jTextField11.getText() + "','" + jTextField10.getText() + "','" + jTextField14.getText() + "','" + jTextField15.getText() + "')";
                    int t = stmt.executeUpdate(j);
                    stmt.close();

                } catch (SQLException y) {
                    JOptionPane.showMessageDialog(null, y);
                }
                Date d = new Date();
                System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                System.out.println("Se han insertado en la tabla clientes los sigientes datos: " + jTextField11.getText() + "','" + jTextField10.getText() + "','" + jTextField14.getText() + "','" + jTextField15.getText());

                jTextField11.setText("");
                jTextField10.setText("");
                jTextField14.setText("");
                jTextField15.setText("");

                escribe = new File("log.txt");

                try {

                    FileWriter f = new FileWriter(escribe, true);
                    BufferedWriter b = new BufferedWriter(f);
                    PrintWriter p = new PrintWriter(b);
                    p.write("Se han insertado datos en la tabla clientes " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                    p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                    p.append("\r\n");
                    p.close();
                    f.close();
                } catch (IOException e) {

                }
            }
        }

    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:

        if ((jTextField3.getText().trim().isEmpty()) || (jTextField4.getText().trim().isEmpty()) || (jTextField5.getText().trim().isEmpty()) || (jTextField6.getText().trim().isEmpty()) || (jTextField7.getText().trim().isEmpty()) || (jTextField8.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(this, "algun campo de texto está vacío");

        } else {
            if (!isInteger(jTextField4.getText()) || !isInteger(jTextField5.getText()) || !isInteger(jTextField6.getText()) || !isInteger(jTextField7.getText()) || !isInteger(jTextField8.getText())) {
                JOptionPane.showMessageDialog(this, "ingrese un valor numerico");
            } else {
                try {

                    Statement stmt = con.createStatement();
                    String j = "insert into empleados values('" + jTextField3.getText() + "','" + jTextField4.getText() + "','" + jTextField5.getText() + "','" + jTextField6.getText() + "','" + jTextField7.getText() + "','" + jTextField8.getText() + "')";
                    int t = stmt.executeUpdate(j);
                    stmt.close();

                } catch (SQLException y) {
                    JOptionPane.showMessageDialog(null, y);
                }

                Date d = new Date();
                System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                System.out.println("Se an insertado en la tabla empleados los sigientes datos: " + jTextField3.getText() + " " + jTextField4.getText() + " " + jTextField5.getText() + " " + jTextField6.getText() + " " + jTextField7.getText() + " " + jTextField8.getText());

                jTextField3.setText("");
                jTextField4.setText("");
                jTextField5.setText("");
                jTextField6.setText("");
                jTextField7.setText("");
                jTextField8.setText("");

                escribe = new File("log.txt");

                try {

                    FileWriter f = new FileWriter(escribe, true);
                    BufferedWriter b = new BufferedWriter(f);
                    PrintWriter p = new PrintWriter(b);
                    p.write("Se han insertado datos en la tabla empleados " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                    p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                    p.append("\r\n");
                    p.close();
                    f.close();
                } catch (IOException e) {

                }
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
        Object[] filas = new Object[jTable2.getColumnCount()];
        try {
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery("select *from empleados");
            while (rs.next()) {

                filas[0] = rs.getString(1);
                filas[1] = rs.getInt(2);
                filas[2] = rs.getInt(3);
                filas[3] = rs.getString(4);
                filas[4] = rs.getInt(5);
                filas[5] = rs.getInt(6);

                tableModel.addRow(filas);
            }
            jPanel6.setVisible(false);
            jPanel4.setVisible(false);
            jPanel3.setVisible(false);
            jPanel2.setVisible(false);
            jPanel5.setVisible(false);
            jPanel7.setVisible(false);
            jPanel8.setVisible(true);
            jPanel9.setVisible(false);

            rs.close();
            stmt.close();
        } catch (SQLException y) {
            JOptionPane.showMessageDialog(null, y);
        }
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("consulta de las tabla Empleados");

        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("consulta de las tabla Empleados " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        jPanel6.setVisible(false);
        jPanel4.setVisible(false);
        jPanel3.setVisible(true);
        jPanel2.setVisible(false);
        jPanel5.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("salio de la consulta de empleado a la interfaz empleado");

        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("salio de la consulta de empleado a la interfaz empleado " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        jPanel6.setVisible(false);
        jPanel4.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
        jPanel5.setVisible(true);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("salio de la consulta de gerente a la interfaz gerente");

        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("Salio de la consulta de gerente a la interfaz gerente " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(true);
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("ingresa a la interfez registrarse ");

        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("ingresa a la interfez registrarse " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("Cerro Sesión ");

        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("Cerro Sesión " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("Cerro Sesión");

        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("Cerro Sesión " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(true);
        jPanel5.setVisible(false);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("Cerro Sesión");

        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("Cerro Sesión " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Date d = new Date();

        if ((jTextField1.getText().trim().isEmpty()) || (jPasswordField2.getText().trim().isEmpty()) || (jPasswordField3.getText().trim().isEmpty())) {
            JOptionPane.showMessageDialog(this, "algun campo de texto está vacío");

        } else {

            if (!isInteger(jTextField1.getText())) {
                JOptionPane.showMessageDialog(this, "ingrese un valor numerico");
            } else {
                if (jPasswordField2.getText().equals(jPasswordField3.getText())) {

                    try {
                        Statement stmt = con.createStatement();
                        String j = "insert into registros values('" + jTextField1.getText() + "','" + jPasswordField2.getText() + "','" + jComboBox2.getSelectedItem() + "')";
                        int t = stmt.executeUpdate(j);
                        stmt.close();

                    } catch (SQLException y) {
                        JOptionPane.showMessageDialog(null, y);
                    }
                    jTextField1.setText("");
                    jPasswordField2.setText("");
                    jPasswordField3.setText("");

                    escribe = new File("log.txt");
                    try {

                        FileWriter f = new FileWriter(escribe, true);
                        BufferedWriter b = new BufferedWriter(f);
                        PrintWriter p = new PrintWriter(b);
                        p.write("se ha registrado un usuario " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                        p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                        p.append("\r\n");
                        p.close();
                        f.close();
                    } catch (IOException e) {

                    }

                    System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                    System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());

                    if (jComboBox2.getSelectedItem() == "empleado") {
                        System.out.println("Se Registro un empleado");
                    } else if (jComboBox2.getSelectedItem() == "cliente") {
                        System.out.println("Se Registro un cliente");
                    } else if (jComboBox2.getSelectedItem() == "gerente") {
                        System.out.println("Se registro un gerente");
                    }
                } else {
                    JOptionPane.showMessageDialog(this, "contraseña incorrecta");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed
    /**
     *
     *
     * @param str String recibe parametro a combertir
     * @return si el string ingresado es numero o no
     */
    public boolean isInteger(String str) {
        try {
            Integer.parseInt(str);
            return true;
        } catch (NumberFormatException nfe) {
        }
        return false;
    }
    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        jPanel4.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
        jPanel5.setVisible(true);
        jPanel6.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("salio de la interfaz registrarse a gerente");

        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("salio de la interfaz registrarse a gerente " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton17ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        jPanel6.setVisible(true);
        jPanel4.setVisible(false);
        jPanel3.setVisible(false);
        jPanel2.setVisible(false);
        jPanel5.setVisible(false);
        jPanel7.setVisible(false);
        jPanel8.setVisible(false);
        jPanel9.setVisible(false);
        Date d = new Date();
        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
        System.out.println("salio de la consulta de cliente a la interfaz cliente");

        escribe = new File("log.txt");
        try {

            FileWriter f = new FileWriter(escribe, true);
            BufferedWriter b = new BufferedWriter(f);
            PrintWriter p = new PrintWriter(b);
            p.write("salio de la consulta de cliente a la interfaz cliente " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
            p.append("\r\n");
            p.close();
            f.close();
        } catch (IOException e) {

        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        // TODO add your handling code here:

        if (jTextField16.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ingrese nombre a eliminar");
        } else {
            try {
                Statement stmt = con.createStatement();
                String j = "delete from empleados where nombre_producto = ('" + jTextField16.getText() + "')";
                int t = stmt.executeUpdate(j);
                stmt.close();

                Date d = new Date();
                System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                System.out.println("Se ha Eliminado el siguiente dato tabla empleados : " + jTextField16.getText());
                jTextField16.setText("");

                try {
                    DefaultTableModel tableModel = (DefaultTableModel) jTable3.getModel();
                    Object[] filas = new Object[jTable3.getColumnCount()];

                    ResultSet rs = stmt.executeQuery("select *from empleados");
                    String a = "";
                    filas[0] = a;
                    filas[1] = a;
                    filas[2] = a;
                    filas[3] = a;
                    filas[4] = a;
                    filas[5] = a;

                    tableModel.addRow(filas);

                    while (rs.next()) {

                        filas[0] = rs.getString(1);
                        filas[1] = rs.getInt(2);
                        filas[2] = rs.getInt(3);
                        filas[3] = rs.getInt(4);
                        filas[4] = rs.getInt(5);
                        filas[5] = rs.getInt(6);

                        tableModel.addRow(filas);
                    }
                    rs.close();
                    stmt.close();

                } catch (SQLException y) {
                    JOptionPane.showMessageDialog(null, y);
                }

                try {

                    FileWriter f = new FileWriter(escribe, true);
                    BufferedWriter b = new BufferedWriter(f);
                    PrintWriter p = new PrintWriter(b);
                    p.write("se han eliminado datos de la tabla empleados " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                    p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                    p.append("\r\n");
                    p.close();
                    f.close();
                } catch (IOException e) {

                }

            } catch (SQLException y) {
                JOptionPane.showMessageDialog(null, y);
            }

        }

    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton19ActionPerformed
        // TODO add your handling code here:
        if (jTextField17.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ingrese nombre a eliminar");
        } else {
            try {
                Statement stmt = con.createStatement();
                String j = "delete from clientes where nombre = ('" + jTextField17.getText() + "')";
                int t = stmt.executeUpdate(j);
                stmt.close();

                Date d = new Date();
                System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                System.out.println("Se ha Eliminado el siguiente dato tabla clientes : " + jTextField17.getText());
                jTextField17.setText("");

                try {
                    DefaultTableModel tableModel = (DefaultTableModel) jTable4.getModel();
                    Object[] filas = new Object[jTable4.getColumnCount()];

                    ResultSet rs = stmt.executeQuery("select *from clientes");
                    String a = "";
                    filas[0] = a;
                    filas[1] = a;
                    filas[2] = a;
                    filas[3] = a;

                    tableModel.addRow(filas);

                    while (rs.next()) {

                        filas[0] = rs.getInt(1);
                        filas[1] = rs.getString(2);
                        filas[2] = rs.getString(3);
                        filas[3] = rs.getString(4);

                        tableModel.addRow(filas);
                    }
                    rs.close();
                    stmt.close();

                } catch (SQLException y) {
                    JOptionPane.showMessageDialog(null, y);
                }

                try {

                    FileWriter f = new FileWriter(escribe, true);
                    BufferedWriter b = new BufferedWriter(f);
                    PrintWriter p = new PrintWriter(b);
                    p.write("se han eliminado datos de la tabla clientes " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                    p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                    p.append("\r\n");
                    p.close();
                    f.close();
                } catch (IOException e) {

                }

            } catch (SQLException y) {
                JOptionPane.showMessageDialog(null, y);
            }

        }

    }//GEN-LAST:event_jButton19ActionPerformed

    private void jButton20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton20ActionPerformed
        // TODO add your handling code here:
        if (jTextField18.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ingrese nombre a eliminar");
        } else {
            try {
                Statement stmt = con.createStatement();
                String j = "delete from cuentas where nombre_deudor = ('" + jTextField18.getText() + "')";
                int t = stmt.executeUpdate(j);
                stmt.close();

                Date d = new Date();
                System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                System.out.println("Se ha Eliminado el siguiente dato tabla cuentas : " + jTextField18.getText());
                jTextField18.setText("");

                try {
                    DefaultTableModel tableModel = (DefaultTableModel) jTable5.getModel();
                    Object[] filas = new Object[jTable5.getColumnCount()];

                    ResultSet rs = stmt.executeQuery("select *from cuentas");
                    String a = "";
                    filas[0] = a;
                    filas[1] = a;
                    filas[2] = a;

                    tableModel.addRow(filas);

                    while (rs.next()) {

                        filas[0] = rs.getString(1);
                        filas[1] = rs.getString(2);
                        filas[2] = rs.getInt(3);

                        tableModel.addRow(filas);
                    }
                    rs.close();
                    stmt.close();

                } catch (SQLException y) {
                    JOptionPane.showMessageDialog(null, y);
                }

                try {

                    FileWriter f = new FileWriter(escribe, true);
                    BufferedWriter b = new BufferedWriter(f);
                    PrintWriter p = new PrintWriter(b);
                    p.write("se han eliminado datos de la tabla cuentas " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                    p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                    p.append("\r\n");
                    p.close();
                    f.close();
                } catch (IOException e) {

                }

            } catch (SQLException y) {
                JOptionPane.showMessageDialog(null, y);
            }

        }
    }//GEN-LAST:event_jButton20ActionPerformed

    private void jButton21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton21ActionPerformed
        // TODO add your handling code here:
        if (jTextField19.getText().trim().isEmpty() || jTextField20.getText().trim().isEmpty() || jTextField21.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ingrese datos a Actualizar");
        } else {

            try {
                Statement stmt = con.createStatement();
                ResultSet rst = stmt.executeQuery("select *from clientes");
                String n = jTextField21.getText();
                while (rst.next()) {
                    if (n.equals(rst.getString(3))) {
                        String j = "update clientes set '" + jTextField19.getText() + "' =  '" + jTextField20.getText() + "' where nombre = '" + jTextField21.getText() + "'";
                        int t = stmt.executeUpdate(j);
                        stmt.close();
                        //" update clientes set cantidad = '"+jTextField19.getText()+"',fecha  = '"+jTextField20.getText()+ "' where nombre = '"+jTextField21.getText()+"'"; 
                        Date d = new Date();
                        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                        System.out.println("Se ha actualizado el siguiente dato tabla clientes : " + jTextField21.getText());
                        jTextField19.setText("");
                        jTextField20.setText("");
                        jTextField21.setText("");

                        try {
                            DefaultTableModel tableModel = (DefaultTableModel) jTable1.getModel();
                            Object[] filas = new Object[jTable1.getColumnCount()];

                            ResultSet rs = stmt.executeQuery("select *from clientes");
                            String a = "";
                            filas[0] = a;
                            filas[1] = a;
                            filas[2] = a;
                            filas[3] = a;

                            tableModel.addRow(filas);

                            while (rs.next()) {

                                filas[0] = rs.getInt(1);
                                filas[1] = rs.getString(2);
                                filas[2] = rs.getString(3);
                                filas[3] = rs.getString(4);

                                tableModel.addRow(filas);
                            }
                            rs.close();
                            stmt.close();

                        } catch (SQLException y) {
                            JOptionPane.showMessageDialog(null, y);
                        }

                        try {

                            FileWriter f = new FileWriter(escribe, true);
                            BufferedWriter b = new BufferedWriter(f);
                            PrintWriter p = new PrintWriter(b);
                            p.write("se han Actualizado datos de la tabla clientes " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                            p.append("\r\n");
                            p.close();
                            f.close();
                        } catch (IOException e) {

                        }
                    }
                }

            } catch (SQLException y) {
                JOptionPane.showMessageDialog(null, "el atributo ingresado no existe");
            }

        }


    }//GEN-LAST:event_jButton21ActionPerformed

    private void jButton22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton22ActionPerformed
        // TODO add your handling code here:
        if (jTextField22.getText().trim().isEmpty() || jTextField23.getText().trim().isEmpty() || jTextField24.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "ingrese datos a Actualizar");
        } else {

            try {
                Statement stmt = con.createStatement();
                ResultSet rst = stmt.executeQuery("select *from empleados");
                String n = jTextField22.getText();
                while (rst.next()) {
                    if (n.equals(rst.getString(1))) {
                        String j = "update empleados set '" + jTextField23.getText() + "' =  '" + jTextField24.getText() + "' where nombre_producto = '" + jTextField22.getText() + "'";
                        int t = stmt.executeUpdate(j);
                        stmt.close();

                        Date d = new Date();
                        System.out.println("Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900));
                        System.out.println("Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                        System.out.println("Se ha actualizado el siguiente dato tabla empleados : " + jTextField22.getText());
                        jTextField22.setText("");
                        jTextField23.setText("");
                        jTextField24.setText("");

                        try {
                            DefaultTableModel tableModel = (DefaultTableModel) jTable2.getModel();
                            Object[] filas = new Object[jTable2.getColumnCount()];

                            ResultSet rs = stmt.executeQuery("select *from empleados");
                            String a = "";
                            filas[0] = a;
                            filas[1] = a;
                            filas[2] = a;
                            filas[3] = a;
                            filas[4] = a;
                            filas[5] = a;

                            tableModel.addRow(filas);

                            while (rs.next()) {

                                filas[0] = rs.getString(1);
                                filas[1] = rs.getInt(2);
                                filas[2] = rs.getInt(3);
                                filas[3] = rs.getInt(4);
                                filas[4] = rs.getInt(5);
                                filas[5] = rs.getInt(6);

                                tableModel.addRow(filas);
                            }
                            rs.close();
                            stmt.close();

                        } catch (SQLException y) {
                            JOptionPane.showMessageDialog(null, y);
                        }

                        try {

                            FileWriter f = new FileWriter(escribe, true);
                            BufferedWriter b = new BufferedWriter(f);
                            PrintWriter p = new PrintWriter(b);
                            p.write("se han Actualizado datos de la tabla empleados " + "Fecha: " + d.getDate() + "/" + (d.getMonth() + 1) + "/" + (d.getYear() + 1900) + " ");
                            p.write("  Hora: " + d.getHours() + ":" + d.getMinutes() + ":" + d.getSeconds());
                            p.append("\r\n");
                            p.close();
                            f.close();
                        } catch (IOException e) {

                        }
                    }
                }

            } catch (SQLException y) {
                JOptionPane.showMessageDialog(null, "el atributo ingresado no existe");
            }

        }

    }//GEN-LAST:event_jButton22ActionPerformed

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        // TODO add your handling code here:
        
         con = sqlite.Conectar(); 
         String path ="/home/adsi/Escritorio/GDI(2)/src/model/views/report1.jasper";
         JasperReport jr = null;
        try {
            jr =  (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,con);
            JasperViewer jv = new JasperViewer(jp);
            jv.setVisible(true);
            jv.setTitle(path);
            con.close();
        } catch (JRException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jButton24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton24ActionPerformed
        // TODO add your handling code here:
        con = sqlite.Conectar(); 
         String path ="/home/adsi/Escritorio/GDI(2)/src/model/views/report2.jasper";
         JasperReport jr = null;
        try {
            jr =  (JasperReport) JRLoader.loadObjectFromFile(path);
            JasperPrint jp = JasperFillManager.fillReport(jr, null,con);
            JasperViewer jv = new JasperViewer(jp);
            jv.setVisible(true);
            jv.setTitle(path);
            con.close();
        } catch (JRException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(Vista.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton24ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton24;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JPasswordField jPasswordField2;
    private javax.swing.JPasswordField jPasswordField3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTable jTable5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

}
